#!/usr/bin/env python3
# Copyright 2026 wangxu
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""
Reference codec for the DS10 application protocol, in pure Python.

This is a second, independent implementation of the wire format defined in
docs/application_protocol_v1.md. It exists for two reasons:

1. Non-ROS peers. A laptop with a serial adapter can talk to the bus without
   building the workspace -- useful for bring-up and for reading a link that
   a ROS node is not attached to.
2. Cross-checking the spec. Two implementations written from the same prose
   disagree exactly where the prose is ambiguous. Both are validated against
   test/protocol_test_vectors.json, whose bytes were derived from the spec by
   hand rather than generated by either codec.

Scope: the `data` field only. Station id, function code, CRC and framing all
belong to the driver (ds10_driver), which builds the Modbus RTU frame around
what these functions return.

Decoders return None on input too short to hold the fixed fields, mirroring
the C++ std::optional. They do not validate reserved flag bits: the spec
requires senders to zero them and receivers to ignore them
(application_protocol_v1.md §flags 字段).
"""

import struct
from typing import Optional

# Wire layouts, as struct format strings. '<' is little-endian throughout.
_SENSOR_DATA_FORMAT = '<BHBf'          # flags, seq, sensor_id, reading
SENSOR_DATA_SIZE = struct.calcsize(_SENSOR_DATA_FORMAT)   # 8
CONTROL_COMMAND_MIN_SIZE = 2           # flags + cmd_id; params may be empty


def encode_control_command(flags: int, cmd_id: int, params: bytes = b'') -> bytes:
    """
    Encode a 0x12 control command.

    Layout: [flags 1B][cmd_id 1B][params ...], no sequence number -- control
    commands are infrequent and deliberately unnumbered
    (application_protocol_v1.md §功能码 0x12).

    :param flags: bit0 requests an ACK; bits 1-7 reserved, send as 0.
    :param cmd_id: application-defined command type.
    :param params: opaque parameter bytes, may be empty.
    :returns: the encoded `data` field.
    """
    return bytes([flags, cmd_id]) + bytes(params)


def decode_control_command(data: bytes) -> Optional[dict]:
    """
    Decode a 0x12 control command.

    :param data: the `data` field, [flags 1B][cmd_id 1B][params ...].
    :returns: dict with flags, cmd_id, params -- or None if shorter than the
        two fixed bytes. Everything past them is params, however long.
    """
    if len(data) < CONTROL_COMMAND_MIN_SIZE:
        return None
    return {
        'flags': data[0],
        'cmd_id': data[1],
        'params': bytes(data[CONTROL_COMMAND_MIN_SIZE:]),
    }


def encode_sensor_data(flags: int, seq: int, sensor_id: int,
                       reading: float) -> bytes:
    """
    Encode a 0x10 sensor report.

    Layout: [flags 1B][seq u16 LE][sensor_id 1B][reading f32 LE], always 8
    bytes (application_protocol_v1.md §功能码 0x10).

    :param flags: bit0 requests an ACK; normally 0 on a high-rate stream.
    :param seq: uint16 sequence number, wrapping at 65535.
    :param sensor_id: application-defined sensor type.
    :param reading: float32 value. inf and nan encode to their IEEE-754 bit
        patterns and survive the round trip; the protocol assigns them no
        special meaning.
    :returns: the encoded `data` field.
    """
    return struct.pack(_SENSOR_DATA_FORMAT, flags, seq, sensor_id, reading)


def decode_sensor_data(data: bytes) -> Optional[dict]:
    """
    Decode a 0x10 sensor report.

    :param data: the `data` field, at least 8 bytes.
    :returns: dict with flags, seq, sensor_id, reading -- or None if shorter
        than 8 bytes. Trailing bytes beyond the eighth are ignored, matching
        the C++ decoder, so a future layout extension stays readable here.
    """
    if len(data) < SENSOR_DATA_SIZE:
        return None
    flags, seq, sensor_id, reading = struct.unpack(
        _SENSOR_DATA_FORMAT, bytes(data[:SENSOR_DATA_SIZE]))
    return {
        'flags': flags,
        'seq': seq,
        'sensor_id': sensor_id,
        'reading': reading,
    }
